CREATE TABLE IF NOT EXISTS users  (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    login varchar(50) NOT NULL UNIQUE,
    email varchar(100) NOT NULL UNIQUE,
    birthday date NOT NULL
);

CREATE TABLE IF NOT EXISTS mpa (
    mpa_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS genres (
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS films (
    film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    name varchar(100) NOT NULL,
    description varchar(1000),
    duration INTEGER NOT NULL CHECK (duration > 0),
    release_date DATE NOT NULL,
    mpa_id varchar(50) REFERENCES mpa (mpa_id)
);


CREATE TABLE IF NOT EXISTS likes (
    film_id BIGINT REFERENCES films,
    user_id BIGINT REFERENCES users

);

CREATE TABLE IF NOT EXISTS friends (
    user_id BIGINT REFERENCES users(user_id),
    friend_id BIGINT REFERENCES users(user_id),
    PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS film_genre (
    film_id BIGINT REFERENCES films(film_id),
    genre_id BIGINT REFERENCES genres(genre_id),
    PRIMARY KEY (film_id, genre_id)
);



